package jmccul;

import jmccul.config.Configuration;
import java.nio.ByteBuffer;
import jmccul.analog.AnalogInputImpl;
import jmccul.analog.AnalogOutputImpl;
import jmccul.config.AnalogInputConfig;
import jmccul.config.AnalogOutputConfig;
import jmccul.config.BoardConfig;
import jmccul.config.CounterConfig;
import jmccul.config.DigitalInputConfig;
import jmccul.config.DigitalOutputConfig;
import jmccul.config.ExpansionConfig;
import jmccul.config.NetworkConfig;
import jmccul.config.TemperatureConfig;
import jmccul.config.WirelessConfig;
import jmccul.counter.CounterImpl;
import jmccul.digital.DigitalImpl;
import jmccul.jna.DaqDeviceDescriptor;
import jmccul.jna.MeasurementComputingUniversalLibrary;
import jmccul.temperature.TemperatureImpl;

/**
 *
 * @author Peter Froud
 */
public class DaqDevice implements AutoCloseable {

    static {
        /*
        There are two ways to set up MC DAQ boards.
        See https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/hh_goto.htm?ULStart.htm#Function_Reference/Ical-APIDetect.htm

        (1) Use InstaCal to detect boards and assign a board number.
            The path to InstaCal is "C:\Program Files (x86)\Measurement Computing\DAQ\inscal32.exe".
            InstaCal saves confugration to a config file on disk at "C:\ProgramData\Measurement Computing\DAQ\CB.CFG".
            Using InstaCal is troublesome for two reasons:
              (a) A human must open InstaCal and click a few buttons when a board is first connected.
              (b) InstaCal settings are sometimes erased, I think during some Windows Update operations.

        (2) Use the Universal Library to detect boards and assign a board number.
            This is better than using InstaCal because the whole thing is totally automatic.


        https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/hh_goto.htm?ULStart.htm#Function_Reference/Device-Discovery/cbIgnoreInstaCal.htm

         The cbIgnoreInstaCal() function tell the MCDAQ driver to ignore the CB.CFG config file
         generated by InstaCal.

         Through experimentation, I have discovered that if you call cbIgnoreInstaCal() after
         opening any devices with cbCreateDaqDevice(), operations on an already openeded board
         will throw error 1028 "Tried to release a board which doesn't exist."
         Therefore we'll use boolean field to make sure we only call cbIgnoreInstaCal() once.
         */
        try {
            final int errorCode = MeasurementComputingUniversalLibrary.INSTANCE.cbIgnoreInstaCal();
            JMCCULUtils.checkError(errorCode);
        } catch (JMCCULException ex) {
            throw new RuntimeException(ex);
        }
    }

    private static int nextBoardNumber = 0;

    private final static int BOARD_NAME_LENGTH = MeasurementComputingUniversalLibrary.BOARDNAMELEN;
    private final static int CONFIG_ITEM_LENGTH = MeasurementComputingUniversalLibrary.BOARDNAMELEN;
    private final static int CONFIG_TYPE_BOARD_INFO = MeasurementComputingUniversalLibrary.BOARDINFO;
    private final static int CONFIG_ITEM_FACTORY_SERIAL_NUMBER = MeasurementComputingUniversalLibrary.BIDEVSERIALNUM;
    private final static int CONFIG_ITEM_USER_DEVICE_ID = MeasurementComputingUniversalLibrary.BIUSERDEVID;

    public final int BOARD_NUMBER;
    public final String FACTORY_SERIAL_NUMBER;
    public final String BOARD_NAME;
    public final int PRODUCT_ID;
//    public final String USER_DEVICE_IDENTIFIER;

    public final DigitalImpl digital;
    public final AnalogOutputImpl analogOutput;
    public final AnalogInputImpl analogInput;
    public final TemperatureImpl temperature;
    public final CounterImpl counter;

    public final AnalogInputConfig analogInputConfig;
    public final AnalogOutputConfig analogOutputConfig;
    public final BoardConfig boardConfig;
    public final CounterConfig counterConfig;
    public final DigitalInputConfig digitalInputConfig;
    public final DigitalOutputConfig digitalOutputConfig;
    public final ExpansionConfig expansionConfig;
    public final NetworkConfig networkConfig;
    public final TemperatureConfig temperatureConfig;
    public final WirelessConfig wirelessConfig;

    public DaqDevice(DaqDeviceDescriptor daqDeviceDescriptor) throws JMCCULException {
        BOARD_NUMBER = nextBoardNumber;

        // https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/hh_goto.htm?ULStart.htm#Function_Reference/Device-Discovery/cbCreateDaqDevice.htm
        final int errorCode = MeasurementComputingUniversalLibrary.INSTANCE.cbCreateDaqDevice(BOARD_NUMBER, daqDeviceDescriptor);

        JMCCULUtils.checkError(errorCode);
        nextBoardNumber++;
        BOARD_NAME = getBoardName();
        FACTORY_SERIAL_NUMBER = getFactorySerialNumber();
        PRODUCT_ID = daqDeviceDescriptor.ProductID;
        //        USER_DEVICE_IDENTIFIER = getUserDeviceIdentifier();

        /*
        if (debugPrintouts) {
        System.out.printf("model=%s, SN=%s assigned to BOARD_NUMBER %d. nextBoardNumber is now %d.\n", desiredBoardName, FACTORY_SERIAL_NUMBER, BOARD_NUMBER, nextBoardNumber);
        }
         */
        digital = new DigitalImpl(this);
        analogOutput = new AnalogOutputImpl(this);
        analogInput = new AnalogInputImpl(this);
        temperature = new TemperatureImpl(this);
        counter = new CounterImpl(this);

        analogInputConfig = new AnalogInputConfig(this);
        analogOutputConfig = new AnalogOutputConfig(this);
        boardConfig = new BoardConfig(this);
        counterConfig = new CounterConfig(this);
        digitalInputConfig = new DigitalInputConfig(this);
        digitalOutputConfig = new DigitalOutputConfig(this);
        expansionConfig = new ExpansionConfig(this);
        networkConfig = new NetworkConfig(this);
        temperatureConfig = new TemperatureConfig(this);
        wirelessConfig = new WirelessConfig(this);
    }

    private String getBoardName() throws JMCCULException {
        final ByteBuffer buf = ByteBuffer.allocate(BOARD_NAME_LENGTH);

        // https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/hh_goto.htm?ULStart.htm#Function_Reference/Miscellaneous_Functions/cbGetBoardName.htm
        final int errorCode = MeasurementComputingUniversalLibrary.INSTANCE.cbGetBoardName(BOARD_NUMBER, buf);

        JMCCULUtils.checkError(errorCode);
        return new String(buf.array()).trim();
    }

    private String getFactorySerialNumber() throws JMCCULException {
        final int DEVICE_NUMBER_BASE_BOARD = 0; //set to 1 to get the factory serial number of an expansion board
        return Configuration.getString(
                CONFIG_TYPE_BOARD_INFO,
                BOARD_NUMBER,
                DEVICE_NUMBER_BASE_BOARD,
                CONFIG_ITEM_FACTORY_SERIAL_NUMBER,
                CONFIG_ITEM_LENGTH
        );

    }

    private String getUserDeviceIdentifier() throws JMCCULException {
        /*
        On a USB-1208FS, this throws error code 41 "This function can not be used with this board".
        In InstaCal you can only set the Identifier field to a number, so I think we need to use
        BIUSERDEVIDNUM.
         */
        final int DEVICE_NUMBER_DEFAULT = 0;
        return Configuration.getString(
                CONFIG_TYPE_BOARD_INFO,
                BOARD_NUMBER,
                DEVICE_NUMBER_DEFAULT,
                CONFIG_ITEM_USER_DEVICE_ID,
                CONFIG_ITEM_LENGTH
        );
    }

    @Override
    public String toString() {
        return "model " + BOARD_NAME + ", serial number " + FACTORY_SERIAL_NUMBER;
    }

    @Override
    public void close() throws JMCCULException {
        // https://www.mccdaq.com/pdfs/manuals/Mcculw_WebHelp/hh_goto.htm?ULStart.htm#Function_Reference/Device-Discovery/cbReleaseDaqDevice.htm
        final int errorCode = MeasurementComputingUniversalLibrary.INSTANCE.cbReleaseDaqDevice(BOARD_NUMBER);
        JMCCULUtils.checkError(errorCode);
    }

}
